[project]
name = "contracts"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts]

[contracts.webauthn-verifier]
path = "contracts/webauthn-verifier.clar"
clarity_version = 5
epoch = "latest"

[contracts.passkey-adapter]
path = "contracts/passkey-adapter.clar"
clarity_version = 5
epoch = "latest"

[contracts.passkey-account]
path = "contracts/passkey-account.clar"
clarity_version = 5
epoch = "latest"

[contracts.passkey-recovery]
path = "contracts/passkey-recovery.clar"
clarity_version = 5
epoch = "latest"

[contracts.passkey-factory]
path = "contracts/passkey-factory.clar"
clarity_version = 5
epoch = "latest"

[contracts.passkey-acc-user1]
path = "contracts/passkey-account.clar"
clarity_version = 5
epoch = "latest"

[contracts.smart-account]
path = "contracts/passkey-account.clar"
clarity_version = 5
epoch = "latest"

[contracts.mock-passkey-app]
path = "tests/fixtures/mock-passkey-app.clar"
clarity_version = 5
epoch = "latest"
